spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: notesappbyusman@gmail.com
    password: ujzjwodxjbaaufvr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false

  datasource:
    url: jdbc:mysql://localhost:3306/chat
    username: usman
    password: uusmann3344

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: debug
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

server:
  error:
    include-stacktrace: on_param
